# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
    branches: [main, master]

name: shiny-deploy

jobs:
  shiny-deploy:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT:       ${{ secrets.GITHUB_TOKEN }}
      RSCONNECT_TOKEN:  ${{ secrets.RSCONNECT_TOKEN }}
      RSCONNECT_SECRET: ${{ secrets.RSCONNECT_SECRET }}
      CLOUD_USER:       ${{ secrets.CLOUD_USER }}
      CLOUD_PASS:       ${{ secrets.CLOUD_PASS }}
    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with: 
          packages: XML
          extra-packages: any::rsconnect
          needs: check 

      - name: Create environment file
        run: |
          touch .Renviron
          echo CLOUD_USER=${{ secrets.CLOUD_USER }} >> .Renviron
          echo CLOUD_PASS=${{ secrets.CLOUD_PASS }} >> .Renviron
          cat .Renviron


      - name: Authorize and deploy app
        run: |
          rsconnect::setAccountInfo(name = 'tarensanders', token = Sys.getenv("RSCONNECT_TOKEN"), secret = Sys.getenv("RSCONNECT_SECRET"))
          rsconnect::deployApp()
        shell: Rscript {0}